"""
Django settings for flow project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read secrets from environment / .env
try:
    from decouple import config, Csv
except Exception:  # pragma: no cover
    config = None
    Csv = None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECRET_KEY: read from environment; falls back to insecure dev key ONLY when
# decouple is unavailable (e.g. bare-bones local run without .env).
SECRET_KEY = (
    config("SECRET_KEY", default="")
    if config
    else os.environ.get("SECRET_KEY", "")
) or "django-insecure-local-dev-only-key"

# DEBUG: always False in production; cast from env string to bool.
DEBUG = (
    config("DEBUG", default=False, cast=bool)
    if config
    else os.environ.get("DEBUG", "False").lower() in ("true", "1", "yes")
)

# ALLOWED_HOSTS: comma-separated list in env, empty list default.
if config and Csv:
    ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="", cast=Csv())
else:
    _hosts_raw = os.environ.get("ALLOWED_HOSTS", "")
    ALLOWED_HOSTS = [h.strip() for h in _hosts_raw.split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'core',
    'theme',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'flow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'flow.wsgi.application'

TAILWIND_APP_NAME = "theme"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if config and config("DATABASE_URL", default=""):
    # Production: PostgreSQL on Neon/cloud
    import urllib.parse
    url = config("DATABASE_URL")
    result = urllib.parse.urlparse(url)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": result.path[1:],
            "USER": result.username,
            "PASSWORD": result.password,
            "HOST": result.hostname,
            "PORT": result.port or 5432,
            "OPTIONS": {"sslmode": "require"},
        }
    }
elif config and config("DB_ENGINE", default="").lower() == "mysql":
    # Local: MySQL (unchanged for local devs who use MySQL)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": config("DB_NAME"),
            "USER": config("DB_USER"),
            "PASSWORD": config("DB_PASSWORD"),
            "HOST": config("DB_HOST", default="127.0.0.1"),
            "PORT": config("DB_PORT", default="3306"),
            "OPTIONS": {"charset": "utf8mb4"},
        }
    }
else:
    # Fallback: SQLite for quick local testing
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

import sys
if "test" in sys.argv or "pytest" in sys.modules:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db_test.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Third-party APIs
NEWSAPI_KEY = (
    config("NEWSAPI_KEY", default="")
    if config
    else os.environ.get("NEWSAPI_KEY", "")
)


STATIC_ROOT = BASE_DIR / "staticfiles"

# Whitenoise for serving static files on Vercel
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Authentication
LOGIN_URL = "/login/"

# ---------------------------------------------------------------------------
# Security & Session hardening (production)
# ---------------------------------------------------------------------------
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG